all:
	#gcc -o test01 src/test01.c src/file.c src/preprocessing.c -I./include
	gcc -o wordreconstruction src/wordreconstruction.c src/matrix.c src/file.c src/bam.c src/preprocessing.c -I./include

clean:
	find -name "*~" -exec rm -rf {} \;
